version: '3'
services:
  service:
    build: app
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - theatre-db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - service

  theatre-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_db
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  static_volume:






