version: '3.8'

services:
  service:
    build: app
    expose:
      - "8000"
    env_file:
      - ./.env
    command: >
      sh -c "
      dockerize -wait tcp://theatre-db:5432 -timeout 30s
      "
    depends_on:
      - theatre-db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - service
    restart: always

  theatre-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  static_volume: